version: '3.4'

services:
  iot1:
    container_name: app
    image: ${DOCKER_REGISTRY-}iot1
    build:
      context: ./iot1
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
  niot1:
    container_name: node
    image: ${DOCKER_REGISTRY-}niot1
    build:
      context: ./niot1
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
